export const skills = [
    { title: 'Computer Arithmetic'},
    { title: 'Arianna'},
    { title: 'ARINC 653'},
    { title: 'WAI-ARIA'},
    { title: 'ARM'},
    { title: 'Army'},
    { title: 'C-arm'},
    { title: 'ARM Cortex-M'},
    { title: 'Small Arms'},
    { title: 'Faro Arm'},
    { title: 'Glock Armorer'},
    { title: 'Arms Control'},
    { title: 'Small Arms Instruction'},
    { title: 'Armenian'},
    { title: 'ARM Assembly'},
    { title: 'Law of Armed Conflict'},
    { title: 'Armor'},
    { title: 'ARMA'},
    { title: 'Aromatherapy'},
    { title: 'Turn Around Management'},
    { title: 'Business Turn-arounds'},
    { title: 'Turn-around Situations'},
    { title: 'Aromatics'},
    { title: 'Company Turn Around'},
    { title: 'Corporate turn-around'},
    { title: 'Project Turn-around'},
    { title: 'ARP'},
    { title: 'ARPA'},
    { title: 'Travel Arrangements'},
    { title: 'Arranging'},
    { title: 'ARRT'},
    { title: 'Flower Arrangements'},
    { title: 'Disk Arrays'},
    { title: 'Arri Alexa'},
    { title: 'Phased Array'},
    { title: 'String Arrangements'},
    { title: 'Company Voluntary Arrangements'},
            { title: 'Voluntary Arrangements'},
    { title: 'Arri'},
    { title: 'ARRA'},
    { title: 'Arriflex'},
    { title: 'Shareholder Arrangements'},
    { title: 'Array Processing'},
    { title: 'Schemes Of Arrangement'},
    { title: 'Microphone Arrays'},
    { title: 'Array Formulas'},
    { title: 'Arson'},
    { title: 'Arsenic'},
    { title: 'Art'},
    { title: 'Art Direction'},
    { title: 'Fine Art'},
    { title: 'Contemporary Art'},
    { title: 'Visual Arts'},
    { title: 'Art History'},
    { title: 'Performing Arts'},
    { title: 'Art Education'},
    { title: 'Fine Art Photography'},
    { title: 'Feature Articles'},
    { title: 'Art Exhibitions'},
    { title: 'Makeup Artistry'},
    { title: 'Arts Administration'},
    { title: 'Artificial Intelligence'},
    { title: 'Public Art'},
    { title: 'Language Arts'},
    { title: 'Figurative Art'},
    { title: 'Studio Art'},
    { title: 'Digital Art'},
    { title: 'Modern Art'},
    { title: 'Aruba Wireless'},
];
